import { createEnv } from '@t3-oss/env-nextjs';
import { z } from 'zod';

export const env = createEnv({
	server: {
		GITHUB_TOKEN: z.string().min(1).startsWith('github_pat'),
		GITHUB_USERNAME: z.string().min(1),
		GITHUB_REPO: z.string().min(1),
		WAKATIME_API_KEY: z.string().min(1).startsWith('waka'),
		WAKATIME_DATA_URL: z.string().url(),
		WAKATIME_DATA_SHARE_URL: z.string().url(),
		RESEND_API_KEY: z.string().min(1).startsWith('re'),
		UMAMI_USER_ID: z.string().min(1),
		UMAMI_WEBSITE_ID: z.string().min(1),
		UMAMI_API_KEY: z.string().min(1),
		UMAMI_API_CLIENT_ENDPOINT: z.string().url(),
		UMAMI_SCRIPT: z.string().url(),
		UMAMI_PREVIEW_ENDPOINT: z.string().url(),
		TURBO_TOKEN: z.string().min(1),
		TURBO_TEAM: z.string().min(1),
		UPSTASH_REDIS_REST_URL: z.string().url(),
		UPSTASH_REDIS_REST_TOKEN: z.string().min(1),
	},
	runtimeEnv: {
		GITHUB_TOKEN: process.env.GITHUB_TOKEN,
		GITHUB_USERNAME: process.env.GITHUB_USERNAME,
		GITHUB_REPO: process.env.GITHUB_REPO,
		WAKATIME_API_KEY: process.env.WAKATIME_API_KEY,
		WAKATIME_DATA_URL: process.env.WAKATIME_DATA_URL,
		WAKATIME_DATA_SHARE_URL: process.env.WAKATIME_DATA_SHARE_URL,
		RESEND_API_KEY: process.env.RESEND_API_KEY,
		UMAMI_USER_ID: process.env.UMAMI_USER_ID,
		UMAMI_WEBSITE_ID: process.env.UMAMI_WEBSITE_ID,
		UMAMI_API_KEY: process.env.UMAMI_API_KEY,
		UMAMI_API_CLIENT_ENDPOINT: process.env.UMAMI_API_CLIENT_ENDPOINT,
		UMAMI_SCRIPT: process.env.UMAMI_SCRIPT,
		UMAMI_PREVIEW_ENDPOINT: process.env.UMAMI_PREVIEW_ENDPOINT,
		TURBO_TOKEN: process.env.TURBO_TOKEN,
		TURBO_TEAM: process.env.TURBO_TEAM,
		UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL,
		UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN,
	},
});
